version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
      - export AWS_ACCESS_KEY_ID=AKIAXTT4BLQKC6LVO4CH
      - export AWS_SECRET_ACCESS_KEY=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
      - ls -lrt
      - cd pim_app
      - ls -lrt
      - python -m venv .venv
      - . .venv/bin/activate
      - pip install zappa
      - ls -lrt
      - cp ../zappa_settings.json ./
      - zappa deploy dev

      
